/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bc_utils_filesystem_FileUtils */

#ifndef _Included_bc_utils_filesystem_FileUtils
#define _Included_bc_utils_filesystem_FileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bc_utils_filesystem_FileUtils
 * Method:    deleteToRecycleBin
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bc_utils_filesystem_FileUtils_deleteToRecycleBin
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
